# Generated by Django 4.2.6 on 2023-10-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dress',
            old_name='dresscolour',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dress',
            old_name='dressname',
            new_name='dname',
        ),
        migrations.RenameField(
            model_name='dress',
            old_name='dressphoto',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='dress',
            old_name='dresstype',
            new_name='skintone',
        ),
        migrations.AddField(
            model_name='dress',
            name='CATEGORY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mydress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressphoto', models.CharField(max_length=300)),
                ('dresstype', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
