# Generated by Django 3.0 on 2024-03-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20240310_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occassion',
            name='DRESS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Dress'),
        ),
    ]
