# Generated by Django 3.0 on 2024-03-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240310_0529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occassion',
        ),
    ]
