# Generated by Django 3.0 on 2024-03-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_occassion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='occasions',
            field=models.CharField(default='', max_length=100),
        ),
    ]
